# Generated by Django 3.0.7 on 2020-07-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('treatments', models.CharField(max_length=1024, null=True)),
                ('remedies', models.CharField(max_length=1024, null=True)),
                ('department', models.ManyToManyField(null=True, to='healthapp.Department')),
            ],
        ),
    ]
