from django import forms


class MainSymptomForm(forms.Form):
    COMMON_SYMPTOMS = [('itching', 'Itching'),
                     ('skin_rash', 'Skin Rash'),
                     ('continuous_sneezing', 'Continuous Sneezing'),
                     ('chills', 'Chills'),
                     ('joint_pain', 'Joint Pain'),
                     ('stomach_pain', 'Stomach Pain'),
                     ('acidity', 'Acidity'),
                     ('vomiting', 'Vomiting'),
                     ('fatigue', 'Fatigue'),
                     ('weight_gain', 'Weight Gain'),
                     ('anxiety', 'Anxiety'),
                     ('cold_hands_and_feets', 'Cold Hands And Feets'),
                     ('mood_swings', 'Mood Swings'),
                     ('weight_loss', 'Weight Loss'),
                     ('restlessness', 'Restlessness'),
                     ('lethargy', 'Lethargy'),
                     ('irregular_sugar_level', 'Irregular Sugar Level'),
                     ('cough', 'Cough'),
                     ('high_fever', 'High Fever'),
                     ('breathlessness', 'Breathlessness'),
                     ('sweating', 'Sweating'),
                     ('indigestion', 'Indigestion'),
                     ('headache', 'Headache'),
                     ('yellowish_skin', 'Yellowish Skin'),
                     ('dark_urine', 'Dark Urine'),
                     ('nausea', 'Nausea'),
                     ('loss_of_appetite', 'Loss Of Appetite'),
                     ('pain_behind_the_eyes', 'Pain Behind The Eyes'),
                     ('back_pain', 'Back Pain'),
                     ('constipation', 'Constipation'),
                     ('abdominal_pain', 'Abdominal Pain'),
                     ('diarrhoea', 'Diarrhoea'),
                     ('mild_fever', 'Mild Fever'),
                     ('yellow_urine', 'Yellow Urine'),
                     ('yellowing_of_eyes', 'Yellowing Of Eyes'),
                     ('acute_liver_failure', 'Acute Liver Failure'),
                     ('swelling_of_stomach', 'Swelling Of Stomach'),
                     ('swelled_lymph_nodes', 'Swelled Lymph Nodes'),
                     ('malaise', 'Malaise'),
                     ('blurred_and_distorted_vision', 'Blurred And Distorted Vision'),
                     ('phlegm', 'Phlegm'),
                     ('throat_irritation', 'Throat Irritation'),
                     ('redness_of_eyes', 'Redness Of Eyes'),
                     ('sinus_pressure', 'Sinus Pressure'),
                     ('runny_nose', 'Runny Nose'),
                     ('congestion', 'Congestion'),
                     ('chest_pain', 'Chest Pain'),
                     ('fast_heart_rate', 'Fast Heart Rate'),
                     ('pain_during_bowel_movements', 'Pain During Bowel Movements'),
                     ('pain_in_anal_region', 'Pain In Anal Region'),
                     ('bloody_stool', 'Bloody Stool'),
                     ('irritation_in_anus', 'Irritation In Anus'),
                     ('neck_pain', 'Neck Pain'),
                     ('dizziness', 'Dizziness'),
                     ('cramps', 'Cramps'),
                     ('bruising', 'Bruising'),
                     ('obesity', 'Obesity'),
                     ('swollen_legs', 'Swollen Legs'),
                     ('puffy_face_and_eyes', 'Puffy Face And Eyes'),
                     ('enlarged_thyroid', 'Enlarged Thyroid'),
                     ('brittle_nails', 'Brittle Nails'),
                     ('swollen_extremeties', 'Swollen Extremeties'),
                     ('excessive_hunger', 'Excessive Hunger'),
                     ('drying_and_tingling_lips', 'Drying And Tingling Lips'),
                     ('slurred_speech', 'Slurred Speech'),
                     ('knee_pain', 'Knee Pain'),
                     ('hip_joint_pain', 'Hip Joint Pain'),
                     ('muscle_weakness', 'Muscle Weakness'),
                     ('stiff_neck', 'Stiff Neck'),
                     ('swelling_joints', 'Swelling Joints'),
                     ('movement_stiffness', 'Movement Stiffness'),
                     ('loss_of_balance', 'Loss Of Balance'),
                     ('unsteadiness', 'Unsteadiness'),
                     ('loss_of_smell', 'Loss Of Smell'),
                     ('bladder_discomfort', 'Bladder Discomfort'),
                     ('continuous_feel_of_urine', 'Continuous Feel Of Urine'),
                     ('passage_of_gases', 'Passage Of Gases'),
                     ('internal_itching', 'Internal Itching'),
                     ('toxic_look_(typhos)', 'Toxic Look (Typhos)'),
                     ('depression', 'Depression'),
                     ('irritability', 'Irritability'),
                     ('muscle_pain', 'Muscle Pain'),
                     ('red_spots_over_body', 'Red Spots Over Body'),
                     ('belly_pain', 'Belly Pain'),
                     ('abnormal_menstruation', 'Abnormal Menstruation'),
                     ('increased_appetite', 'Increased Appetite'),
                     ('polyuria', 'Polyuria'),
                     ('family_history', 'Family History'),
                     ('mucoid_sputum', 'Mucoid Sputum'),
                     ('rusty_sputum', 'Rusty Sputum'),
                     ('lack_of_concentration', 'Lack Of Concentration'),
                     ('visual_disturbances', 'Visual Disturbances'),
                     ('receiving_blood_transfusion', 'Receiving Blood Transfusion'),
                     ('receiving_unsterile_injections', 'Receiving Unsterile Injections'),
                     ('coma', 'Coma'),
                     ('stomach_bleeding', 'Stomach Bleeding'),
                     ('distention_of_abdomen', 'Distention Of Abdomen'),
                     ('history_of_alcohol_consumption', 'History Of Alcohol Consumption'),
                     ('fluid_overload', 'Fluid Overload'),
                     ('blood_in_sputum', 'Blood In Sputum'),
                     ('prominent_veins_on_calf', 'Prominent Veins On Calf'),
                     ('palpitations', 'Palpitations'),
                     ('painful_walking', 'Painful Walking'),
                     ('skin_peeling', 'Skin Peeling'),
                     ('silver_like_dusting', 'Silver Like Dusting'),
                     ('small_dents_in_nails', 'Small Dents In Nails'),
                     ('inflammatory_nails', 'Inflammatory Nails'),
                     ('blister', 'Blister'),
                     ('red_sore_around_nose', 'Red Sore Around Nose'),
                     ('yellow_crust_ooze', 'Yellow Crust Ooze')]
    symptom = forms.ChoiceField(choices=COMMON_SYMPTOMS)


class RelatedSymptomForm(forms.Form):
    def __init__(self, *args, request=None, **kwargs):
        super(RelatedSymptomForm, self).__init__(*args, **kwargs)
        self.request = request
        rel_list = []
        if request is not None:
            rel_list = request.session.get('related', list())
            RELATED = []
            for each in rel_list:
                RELATED.append((each, " ".join(each.split('_')).title()))

        self.fields['symptoms'] = forms.MultipleChoiceField(choices=RELATED, widget=forms.CheckboxSelectMultiple())
